### ISSUE TITLE
the new map systerm has big problem

### ISSUE THREAD

**Issue by xfury** [mangos/Extractor_projects#1]
i test the new map systerm.
the creature will often target home during the combat.
i think is the LOS systerm problem.
maybe out of LOS so the creature target home?
the creature perform well on old map systerm.
I think something must be wrong in the new map systerm.
But i'm new here .i do not know how to fix the map systerm.
I can just test and report.

**Comment by billy1arm** [comment]
@xfury - I did a lot of tests with maps built on the commit prior to initial commit and also noticed a strange LOS / evade issue, This seemed unchanged after the new maps were built

Which core were you using ?

**Comment by xfury** [comment]
@billy1arm Mangoszero R21 lastest commit [Fix] non initialised variable. Thanks xfury

**Comment by H0zen** [comment]
@billy1arm 
https://github.com/mangos/Extractor_projects/blob/master/Movemap-Generator/MapBuilder.cpp#L609
Those commented directives make troubles

**Comment by billy1arm** [comment]
@H0zen - Is it the commented directives causing the problem or the code chunk causing the problem ?

**Comment by H0zen** [comment]
@billy1arm - after experiencing strange and funny issues with the new mmaps (like pigs in the air, npcs vanishing under terrain and so on) I made some diffs between old and new code. The only significant addition was that code chunk. After I removed it (uncommenting those directives) and rebuilding mmaps, the issues disapeared. Also, looking at the server`s code, I noticed that some time ago, a subtle typo went unnoticed ( https://github.com/mangoszero/server/blob/develop21/src/game/WorldHandlers/GridMap.h#L289 ).

**Comment by billy1arm** [comment]
@H0zen 
should:
    class TerrainManager : public MaNGOS::Singleton<TerrainManager>, MaNGOS::ClassLevelLockable<TerrainManager, ACE_Thread_Mutex>

be

    class TerrainManager : public MaNGOS::Singleton<TerrainManager>, MaNGOS::ClassLevelLockable<TerrainManager>, ACE_Thread_Mutex

?

**Comment by H0zen** [comment]
@billy1arm should be: 
'class TerrainManager : public MaNGOS::Singleton<TerrainManager, MaNGOS::ClassLevelLockable<TerrainManager>, ACE_Thread_Mutex> >

**Comment by billy1arm** [comment]
@H0zen - I just attempted to build after this change with eluna enabled and it generated 85 errors, any ideas ?

**Comment by H0zen** [comment]
@billy1arm  sorry, my bad :( the right code:
```
class TerrainManager : public MaNGOS::Singleton<TerrainManager, MaNGOS::ClassLevelLockable<TerrainManager, ACE_Thread_Mutex> >
```

**Comment by H0zen** [comment]
Should be
'class TerrainManager : public MaNGOS::Singleton<TerrainManager, MaNGOS::ClassLevelLockable<TerrainManager>, ACE_Thread_Mutex> >'






Antz <notifications@github.com> a scris:

@H0zen 
should:
class TerrainManager : public MaNGOS::Singleton, MaNGOS::ClassLevelLockable
be
class TerrainManager : public MaNGOS::Singleton<TerrainManager>, MaNGOS::ClassLevelLockable<TerrainManager>, ACE_Thread_Mutex 
?

**Comment by billy1arm** [comment]
@xfury / @H0zen - Have the latest revisions resolved the issues ?

**Comment by xfury** [comment]
i will test tomorrow.
if ok i will report the result

**Comment by H0zen** [comment]
Latest tests seem ok (from my point of view)

**Comment by billy1arm** [comment]
Pretty sure this is ok now.
